name: ClimTest

channels:
  - conda-forge

dependencies:
  - python=3.8.8
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pip

  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - scipy
