name: ClimTest

channels:
  - conda-forge

dependencies:
  - python=3.8.8
  - numpy=1.20.2
  - scipy=1.6.2
  - matplotlib=3.4.1
  - pandas=1.2.4
  - pip=21.0.1

  - pip:
    - nbgitpuller=0.9.0
    - sphinx-gallery=0.9.0
    - pandas=1.2.4
    - matplotlib=3.4.1
    - scipy=1.6.2
